import { theme, safeZone } from "./theme";

export const mosaicStyles = {
  container: {
    backgroundColor: theme.colors.bg,
    paddingTop: safeZone.top,
    paddingBottom: 0,
    paddingLeft: 64,
    paddingRight: 40,
    display: "flex",
    flexDirection: "column" as const,
  },
  header: {
    marginBottom: 24,
    flexShrink: 0,
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    marginBottom: 6,
  },
  handle: {
    color: theme.colors.accent,
    fontSize: 22,
    fontFamily: theme.fonts.main,
    fontWeight: 700,
    letterSpacing: 4,
    textTransform: "uppercase" as const,
  },
  date: {
    color: theme.colors.muted,
    fontSize: 20,
    fontFamily: theme.fonts.mono,
  },
  title: {
    color: theme.colors.text,
    fontSize: 52,
    fontFamily: theme.fonts.main,
    fontWeight: 700,
  },
  divider: {
    height: 3,
    backgroundColor: theme.colors.accent,
    borderRadius: 2,
    marginBottom: 28,
    flexShrink: 0,
  },
  grid: {
    flex: 1,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "repeat(4, 1fr)",
    gap: 16,
    minHeight: 0,
    paddingRight: safeZone.right,
    marginBottom: 28,
  },
  card: {
    position: "relative" as const,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: theme.colors.surface,
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "stretch",
  },
  cardArtContainer: {
    width: "48%",
    flexShrink: 0,
    backgroundColor: "#11131A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  cardArt: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain" as const,
    borderRadius: 6,
  },
  cardInfo: {
    flex: 1,
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "space-between",
    minHeight: 0,
    overflow: "hidden",
  },
  cardNameSection: {
    minHeight: 0,
  },
  rank: {
    color: theme.colors.accent,
    fontSize: 22,
    fontFamily: theme.fonts.mono,
    fontWeight: 700,
    marginBottom: 4,
  },
  cardName: {
    color: theme.colors.text,
    fontSize: 18,
    fontFamily: theme.fonts.main,
    fontWeight: 700,
    lineHeight: 1.15,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  priceSection: {
    flexShrink: 0,
  },
  marketLabel: {
    color: theme.colors.muted,
    fontSize: 16,
    fontFamily: theme.fonts.mono,
    marginBottom: 4,
    letterSpacing: 1,
  },
  price: {
    color: theme.colors.text,
    fontSize: 26,
    fontFamily: theme.fonts.mono,
    fontWeight: 700,
    marginBottom: 8,
  },
  changeText: (isUp: boolean) => ({
    color: isUp ? "#22C55E" : "#EF4444",
    fontSize: 22,
    fontFamily: theme.fonts.mono,
    fontWeight: 700,
  }),
  movementBadge: (color: string) => ({
    border: `1px solid ${color}`,
    color,
    fontSize: 16,
    fontFamily: theme.fonts.mono,
    fontWeight: 700,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 4,
    letterSpacing: 1.5,
    alignSelf: "flex-start" as const,
  }),
  accentLine: {
    height: 4,
    backgroundColor: theme.colors.accent,
    flexShrink: 0,
  },
  bottomSection: {
    height: 350,
    backgroundColor: theme.colors.bg,
    flexShrink: 0,
  },
} as const;
